# Generated by Django 5.2.5 on 2025-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(choices=[('cctv', 'CCTV Installation'), ('alarm', 'Alarm System'), ('access', 'Access Control'), ('monitoring', '24/7 Monitoring')], max_length=100),
        ),
    ]
